name: Build and Deploy

on:
  push:
    tags:
      - v0.*.*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'

      - name: Build Jar
        run: ./gradlew shadowJar

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "fireplace.jar"
          target: ${{ secrets.REMOTE_TARGET }}

      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ${{ secrets.RESTART_SCRIPT }}
